<?php

namespace Database\Seeders;

use App\Models\SignalSource;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SignalSourceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sources = [
            // HIGH PRIORITY - Hiring & Jobs
            [
                'name' => 'LinkedIn',
                'slug' => 'linkedin',
                'type' => 'social',
                'description' => 'Job postings, hiring announcements, and professional profile updates',
                'category' => ['hiring', 'social', 'professional', 'networking'],
                'url' => 'https://linkedin.com',
                'auth_required' => true,
                'cost_tier' => 'enterprise',
                'frequency_options' => ['hourly', 'daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'Requires LinkedIn API access and OAuth setup',
                'priority' => 100,
            ],
            [
                'name' => 'Indeed',
                'slug' => 'indeed',
                'type' => 'jobs',
                'description' => 'Job listings and hiring trends',
                'category' => ['hiring', 'jobs'],
                'url' => 'https://indeed.com',
                'auth_required' => false,
                'cost_tier' => 'free',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'Web scraping or API integration',
                'priority' => 85,
            ],
            [
                'name' => 'CareerHQ',
                'slug' => 'careerhq',
                'type' => 'jobs',
                'description' => 'Association and nonprofit job listings and career resources',
                'category' => ['hiring', 'jobs', 'nonprofit', 'associations'],
                'url' => 'https://careerhq.asaecenter.org/',
                'auth_required' => false,
                'cost_tier' => 'free',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'Web scraping or RSS feed integration',
                'priority' => 80,
            ],

            // HIGH PRIORITY - Product Launches
            [
                'name' => 'Product Hunt',
                'slug' => 'product-hunt',
                'type' => 'product',
                'description' => 'New product launches and feature announcements',
                'category' => ['product', 'launches'],
                'url' => 'https://producthunt.com',
                'auth_required' => false,
                'cost_tier' => 'free',
                'frequency_options' => ['hourly', 'daily'],
                'status' => 'active',
                'setup_instructions' => 'Product Hunt API access',
                'priority' => 95,
            ],
            [
                'name' => 'News API',
                'slug' => 'news-api',
                'type' => 'news',
                'description' => 'News articles and press releases by keyword',
                'category' => ['news', 'press'],
                'url' => 'https://newsapi.org',
                'auth_required' => true,
                'cost_tier' => 'free',
                'frequency_options' => ['hourly', 'daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'Sign up for free API key at newsapi.org',
                'priority' => 90,
            ],

            // HIGH PRIORITY - Code & Technical
            [
                'name' => 'GitHub Trending',
                'slug' => 'github-trending',
                'type' => 'technical',
                'description' => 'Trending repositories and GitHub activity by keyword',
                'category' => ['code', 'technical'],
                'url' => 'https://github.com/trending',
                'auth_required' => false,
                'cost_tier' => 'free',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'GitHub API or web scraping',
                'priority' => 88,
            ],
            [
                'name' => 'GitHub Search',
                'slug' => 'github-search',
                'type' => 'technical',
                'description' => 'Search repositories, issues, and pull requests',
                'category' => ['code', 'technical'],
                'url' => 'https://github.com/search',
                'auth_required' => false,
                'cost_tier' => 'free',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'GitHub API v3 or v4 (GraphQL)',
                'priority' => 85,
            ],

            // MEDIUM PRIORITY - Social & Community
            [
                'name' => 'Twitter/X',
                'slug' => 'twitter',
                'type' => 'social',
                'description' => 'Tweet search and hashtag monitoring',
                'category' => ['community', 'social'],
                'url' => 'https://twitter.com',
                'auth_required' => true,
                'cost_tier' => 'premium',
                'frequency_options' => ['realtime', 'hourly', 'daily'],
                'status' => 'active',
                'setup_instructions' => 'Twitter API v2 with elevated access',
                'priority' => 75,
            ],
            [
                'name' => 'HackerNews',
                'slug' => 'hackernews',
                'type' => 'community',
                'description' => 'Tech news and discussion threads',
                'category' => ['community', 'social'],
                'url' => 'https://news.ycombinator.com',
                'auth_required' => false,
                'cost_tier' => 'free',
                'frequency_options' => ['hourly', 'daily'],
                'status' => 'active',
                'setup_instructions' => 'HackerNews API (official)',
                'priority' => 70,
            ],
            [
                'name' => 'Dev.to',
                'slug' => 'devto',
                'type' => 'content',
                'description' => 'Developer articles and technical blogs',
                'category' => ['content', 'technical'],
                'url' => 'https://dev.to',
                'auth_required' => false,
                'cost_tier' => 'free',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'Dev.to API',
                'priority' => 65,
            ],
            [
                'name' => 'Reddit',
                'slug' => 'reddit',
                'type' => 'community',
                'description' => 'Subreddit discussions and posts (r/saas, r/startups, etc.)',
                'category' => ['community', 'social'],
                'url' => 'https://reddit.com',
                'auth_required' => false,
                'cost_tier' => 'free',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'Reddit API or PRAW library',
                'priority' => 60,
            ],

            // MEDIUM PRIORITY - Funding & Growth
            [
                'name' => 'Crunchbase',
                'slug' => 'crunchbase',
                'type' => 'funding',
                'description' => 'Funding announcements, company funding rounds, and investor activity',
                'category' => ['funding', 'growth'],
                'url' => 'https://crunchbase.com',
                'auth_required' => true,
                'cost_tier' => 'premium',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'Crunchbase API key or web scraping',
                'priority' => 72,
            ],
            [
                'name' => 'PitchBook',
                'slug' => 'pitchbook',
                'type' => 'funding',
                'description' => 'Funding data, M&A activity, and investor information',
                'category' => ['funding', 'growth'],
                'url' => 'https://pitchbook.com',
                'auth_required' => true,
                'cost_tier' => 'premium',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'inactive',
                'setup_instructions' => 'PitchBook API access',
                'priority' => 70,
            ],

            // MEDIUM PRIORITY - Technical Signals
            [
                'name' => 'Stack Overflow',
                'slug' => 'stackoverflow',
                'type' => 'technical',
                'description' => 'Q&A activity and problem discussions',
                'category' => ['code', 'technical'],
                'url' => 'https://stackoverflow.com',
                'auth_required' => false,
                'cost_tier' => 'free',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'Stack Exchange API',
                'priority' => 65,
            ],
            [
                'name' => 'NPM Registry',
                'slug' => 'npm',
                'type' => 'technical',
                'description' => 'JavaScript package downloads and trends',
                'category' => ['code', 'technical'],
                'url' => 'https://npmjs.com',
                'auth_required' => false,
                'cost_tier' => 'free',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'NPM Registry API',
                'priority' => 60,
            ],
            [
                'name' => 'PyPI',
                'slug' => 'pypi',
                'type' => 'technical',
                'description' => 'Python package downloads and trends',
                'category' => ['code', 'technical'],
                'url' => 'https://pypi.org',
                'auth_required' => false,
                'cost_tier' => 'free',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'PyPI API or BigQuery public dataset',
                'priority' => 60,
            ],

            // LOWER PRIORITY - Events & Speaking
            [
                'name' => 'Lunchclub',
                'slug' => 'lunchclub',
                'type' => 'events',
                'description' => 'Conference speaker lists and event information',
                'category' => ['events', 'networking'],
                'url' => 'https://lunchclub.com',
                'auth_required' => true,
                'cost_tier' => 'premium',
                'frequency_options' => ['weekly'],
                'status' => 'active',
                'setup_instructions' => 'Lunchclub API access',
                'priority' => 50,
            ],
            [
                'name' => 'Eventbrite',
                'slug' => 'eventbrite',
                'type' => 'events',
                'description' => 'Event listings and attendee information',
                'category' => ['events', 'networking'],
                'url' => 'https://eventbrite.com',
                'auth_required' => true,
                'cost_tier' => 'free',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'active',
                'setup_instructions' => 'Eventbrite API',
                'priority' => 50,
            ],

            // LOWER PRIORITY - SEO & Web
            [
                'name' => 'Ahrefs',
                'slug' => 'ahrefs',
                'type' => 'web',
                'description' => 'Website backlinks and content changes',
                'category' => ['web', 'seo'],
                'url' => 'https://ahrefs.com',
                'auth_required' => true,
                'cost_tier' => 'premium',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'inactive',
                'setup_instructions' => 'Ahrefs API access',
                'priority' => 40,
            ],
            [
                'name' => 'Similarweb',
                'slug' => 'similarweb',
                'type' => 'web',
                'description' => 'Website traffic and digital intelligence',
                'category' => ['web', 'seo'],
                'url' => 'https://similarweb.com',
                'auth_required' => true,
                'cost_tier' => 'premium',
                'frequency_options' => ['daily', 'weekly'],
                'status' => 'inactive',
                'setup_instructions' => 'Similarweb API access',
                'priority' => 40,
            ],
        ];

        foreach ($sources as $source) {
            $source['frequency_options'] = json_encode($source['frequency_options']);
            $source['category'] = json_encode($source['category']);
            SignalSource::updateOrCreate(
                ['slug' => $source['slug']],
                $source
            );
        }
    }
}
